/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import control.koneksi;
import control.menuut;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;


/**
 *
 * @author LENOVO
 */
public class MenuUtama extends javax.swing.JFrame {
    koneksi db;
    menuut ut;
    
    public MenuUtama() {
        initComponents();
        db = new koneksi();
        ut = new menuut();
        date();
        setLocationRelativeTo(this);
        setResizable(false);
        ut.tampilcounttrx();
        ut.tampilkeuntungan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Profil = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        level = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        btnuser = new javax.swing.JButton();
        btnbarang = new javax.swing.JButton();
        btnkasir = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        btnreport = new javax.swing.JButton();
        btnsuppliers = new javax.swing.JButton();
        pengguna = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        barang = new javax.swing.JLabel();
        kasir = new javax.swing.JLabel();
        suppliers = new javax.swing.JLabel();
        laporan = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        Total = new javax.swing.JPanel();
        ttltransaksi = new javax.swing.JLabel();
        ttlkeuntungan = new javax.swing.JLabel();
        totaltrx = new javax.swing.JLabel();
        totalkeuntungan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Profil.setBackground(new java.awt.Color(153, 204, 255));
        Profil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_NFT_User_120px.png"))); // NOI18N
        Profil.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        level.setFont(new java.awt.Font("Dubai Medium", 2, 16)); // NOI18N
        level.setForeground(new java.awt.Color(255, 255, 255));
        level.setText("Admin");
        Profil.add(level, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 110, 20));

        jLabel12.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Inventory And Management");
        Profil.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 210, 50));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_management_120px_3.png"))); // NOI18N
        Profil.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 120, 120));

        jLabel14.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("I  M  A  N");
        Profil.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 150, 50));

        nama.setFont(new java.awt.Font("Dubai Medium", 0, 25)); // NOI18N
        nama.setForeground(new java.awt.Color(255, 255, 255));
        nama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nama.setText("Asmodheous");
        Profil.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 340, 50));

        Menu.setBackground(new java.awt.Color(255, 255, 255));
        Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnuser.setBackground(new java.awt.Color(255, 255, 255));
        btnuser.setForeground(new java.awt.Color(255, 255, 255));
        btnuser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_user_folder_120px.png"))); // NOI18N
        btnuser.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 204, 255), new java.awt.Color(153, 204, 255)));
        btnuser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnuser.setOpaque(false);
        btnuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuserActionPerformed(evt);
            }
        });
        Menu.add(btnuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 140, 120));

        btnbarang.setBackground(new java.awt.Color(255, 255, 255));
        btnbarang.setForeground(new java.awt.Color(255, 255, 255));
        btnbarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_shop_120px.png"))); // NOI18N
        btnbarang.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 204, 255), new java.awt.Color(153, 204, 255)));
        btnbarang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnbarang.setOpaque(false);
        btnbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbarangActionPerformed(evt);
            }
        });
        Menu.add(btnbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 140, 120));

        btnkasir.setBackground(new java.awt.Color(255, 255, 255));
        btnkasir.setForeground(new java.awt.Color(255, 255, 255));
        btnkasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_paper_money_120px.png"))); // NOI18N
        btnkasir.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 204, 255), new java.awt.Color(153, 204, 255)));
        btnkasir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnkasir.setOpaque(false);
        btnkasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkasirActionPerformed(evt);
            }
        });
        Menu.add(btnkasir, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 140, 120));

        btnlogout.setBackground(new java.awt.Color(255, 255, 255));
        btnlogout.setForeground(new java.awt.Color(255, 255, 255));
        btnlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_exit_120px.png"))); // NOI18N
        btnlogout.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 204, 255), new java.awt.Color(153, 204, 255)));
        btnlogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlogout.setOpaque(false);
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });
        Menu.add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 140, 120));

        btnreport.setBackground(new java.awt.Color(255, 255, 255));
        btnreport.setForeground(new java.awt.Color(255, 255, 255));
        btnreport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_graph_report_120px.png"))); // NOI18N
        btnreport.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 204, 255), new java.awt.Color(153, 204, 255)));
        btnreport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnreport.setOpaque(false);
        btnreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreportActionPerformed(evt);
            }
        });
        Menu.add(btnreport, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 140, 120));

        btnsuppliers.setBackground(new java.awt.Color(255, 255, 255));
        btnsuppliers.setForeground(new java.awt.Color(255, 255, 255));
        btnsuppliers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_supplier_120px.png"))); // NOI18N
        btnsuppliers.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 204, 255), new java.awt.Color(153, 204, 255)));
        btnsuppliers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsuppliers.setOpaque(false);
        btnsuppliers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuppliersActionPerformed(evt);
            }
        });
        Menu.add(btnsuppliers, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 140, 120));

        pengguna.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        pengguna.setText("Pengguna");
        Menu.add(pengguna, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, -1, -1));

        logout.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        logout.setText("Logout");
        Menu.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 320, -1, -1));

        barang.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        barang.setText("Barang");
        Menu.add(barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, -1, -1));

        kasir.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        kasir.setText("Kasir");
        Menu.add(kasir, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));

        suppliers.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        suppliers.setText("Suppliers");
        Menu.add(suppliers, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, -1));

        laporan.setFont(new java.awt.Font("Dubai Medium", 0, 18)); // NOI18N
        laporan.setText("Laporan");
        Menu.add(laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, -1, -1));

        date.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        date.setEnabled(false);
        Menu.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 260, 30));

        Total.setBackground(new java.awt.Color(0, 0, 102));
        Total.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ttltransaksi.setFont(new java.awt.Font("Dubai Medium", 0, 20)); // NOI18N
        ttltransaksi.setForeground(new java.awt.Color(255, 255, 255));
        ttltransaksi.setText("Total Transaksi :");
        Total.add(ttltransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        ttlkeuntungan.setFont(new java.awt.Font("Dubai Medium", 0, 20)); // NOI18N
        ttlkeuntungan.setForeground(new java.awt.Color(255, 255, 255));
        ttlkeuntungan.setText("Total Keuntungan :");
        Total.add(ttlkeuntungan, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, -1, -1));

        totaltrx.setFont(new java.awt.Font("Dubai Medium", 1, 48)); // NOI18N
        totaltrx.setForeground(new java.awt.Color(255, 255, 255));
        totaltrx.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totaltrx.setText("0");
        totaltrx.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Total.add(totaltrx, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 250, 90));

        totalkeuntungan.setFont(new java.awt.Font("Dubai Medium", 1, 48)); // NOI18N
        totalkeuntungan.setForeground(new java.awt.Color(255, 255, 255));
        totalkeuntungan.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalkeuntungan.setText("0");
        totalkeuntungan.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Total.add(totalkeuntungan, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 290, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Profil, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
                    .addComponent(Total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Profil, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnkasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkasirActionPerformed
        Kasir menu = new Kasir("1");
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnkasirActionPerformed

    private void btnbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbarangActionPerformed
        Barang menu = new Barang();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnbarangActionPerformed

    private void btnuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuserActionPerformed
        Users menu = new Users();
        menu.setVisible(true);
                
    }//GEN-LAST:event_btnuserActionPerformed

    private void btnreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreportActionPerformed
        Laporan menu = new Laporan();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnreportActionPerformed

    private void btnsuppliersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuppliersActionPerformed
       Suppliers menu = new Suppliers();
       menu.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_btnsuppliersActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
       Login menu = new Login();
       String ObjButton[]= {"YES","NO"};
       int pilihan = JOptionPane.showOptionDialog(null, "Apakah Anda yakin ingin keluar ?", "Message", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE,
               null, ObjButton, ObjButton[1]);
       if(pilihan == 0){
           menu.setVisible(true);
           this.setVisible(false);
       }    
    }//GEN-LAST:event_btnlogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }
    
        public void date (){
        Date dt = new Date();
        SimpleDateFormat s = new SimpleDateFormat("EEEEE, dd MM yyyy");
        date.setText(s.format(dt)); 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel Profil;
    private javax.swing.JPanel Total;
    private javax.swing.JLabel barang;
    private javax.swing.JButton btnbarang;
    private javax.swing.JButton btnkasir;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnreport;
    private javax.swing.JButton btnsuppliers;
    private javax.swing.JButton btnuser;
    private javax.swing.JLabel date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel kasir;
    private javax.swing.JLabel laporan;
    public static javax.swing.JLabel level;
    private javax.swing.JLabel logout;
    public static javax.swing.JLabel nama;
    private javax.swing.JLabel pengguna;
    private javax.swing.JLabel suppliers;
    public static javax.swing.JLabel totalkeuntungan;
    public static javax.swing.JLabel totaltrx;
    private javax.swing.JLabel ttlkeuntungan;
    private javax.swing.JLabel ttltransaksi;
    // End of variables declaration//GEN-END:variables
}
